version: '2'

services:
  api:
    image: opentraffic/api:latest
    networks:
      - opentraffic_api
    ports:
      - "8004:8004"
    volumes:
      - ${DATAPATH}:/data
    environment:
      - POSTGRES_PORT=5432
      - POSTGRES_USER=opentraffic
      - POSTGRES_PASSWORD=changeme
      - POSTGRES_DB=opentraffic
      - POSTGRES_HOST=172.17.0.1

networks:
  opentraffic_api:
    driver: bridge
